### ISSUE TITLE
Support referencing steps as components to enable re-usability

### ISSUE THREAD

**Issue by zikani03** [nndi-oss/dialoguss#8]
Support referencing components to enable re-usability.

```yaml
steps:
  - id: 1234567891011
    phoneNumber: 265888123456
    description: "Should return list of visited locations"
    steps:
      - expect: "#/components/steps/initial"
      - userInput: "2"
      
components:
  steps:
    initial: |-
      Welcome
      1. Choose a location
      2. View previous locations
      #. Exit
```

**Comment by ntumbuka** [comment]
I think making some slight adjustments to the spec would make things easier. I am thinking of something like:

```yaml
steps:
  - id: 1234567891011
    phoneNumber: 265888123456
    description: "Should return list of visited locations"
    steps:
      - component: "default/initial"
        userInput: "2"
      - expect: "#/for/some/reason/my/ussd/screen/looks/like/this"
        userInput: "1"
components:
  - namespace: default
    items:
      - name: initial
        expect: |-
          Welcome
          1. Choose a location
          2. View previous locations
          #. Exit
```
- This avoids reusing the `expect` field on the step, so no need to parse its value to determine whether it's a component ref or just plain text.
- Structuring the components in this way makes it easy to unmarshal them into structs.
